<?php

namespace AppBundle\Repository;

/**
 * AgendaStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
