<?php

namespace AppBundle\Repository;

/**
 * MeetingAttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingAttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
