<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use AppBundle\Entity\ProjectRole;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectHasUserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectHasUserRepository extends EntityRepository
{
    public function findIfUserHasRoleInProject(Project $project, ProjectRole $projectRole, User $user)
    {
        return $this->createQueryBuilder('users')
            ->where('users.user = :userP and users.project = :projectP')
            ->setParameters([
                'userP' => $user,
                'projectP' => $project,
                'roleP' => $projectRole
            ]);


    }
}
