
# Project section
new_project:
    path: /project/newproject
    defaults: {_controller : AppBundle:Project:new}
delete_project:
    path: /project/deleteproject/{project}
    defaults: {_controller : AppBundle:Project:delete}
turn_project_lock:
    path: /project/turnprojectlock/{project}
    defaults: {_controller : AppBundle:Project:turnLock}
add_key_users_to_project:
    path: /project/addkeyuserstoproject
    defaults: {_controller : AppBundle:Project:addKeyUsersToProject}

# Project role section
new_project_role:
    path: /role/newrole
    defaults: {_controller: AppBundle:Role:new}
delete_role:
    path: /role/deleterole/{projectRole}
    defaults: {_controller: AppBundle:Role:delete}

#Admin section
new_user:
    path: /admin/newuser
    defaults: {_controller : AppBundle:Admin:new}
edit_user:
    path: /admin/edituser/{userID}
    defaults: {_controller : AppBundle:Admin:edit}
delete_user:
    path: /admin/deleteuser/{userID}
    defaults: {_controller : AppBundle:Admin:delete}

#MAIN CONTROLLER section
sup_panel:
    path: /sup/suppanel
    defaults: {_controller : AppBundle:Main:supPanel}
user_panel:
    path: /user/userpanel
    defaults: {_controller : AppBundle:Main:userPanel}
homepage:
    path: /
    defaults: {_controller : AppBundle:Main:homepage}
admin_panel:
    path: /admin/adminpanel
    defaults: {_controller : AppBundle:Main:adminPanel}
logout:
    path: /logout
    defaults: { _controller : AppBundle:Main:logout}