#app_agenda_item:
#    resource: "@AppBundle/Controller/AgendaItemController.php"
#    type:     annotation

#app_meeting_attendance:
#    resource: "@AppBundle/Controller/MeetingAttendanceController.php"
#    type:     annotation

#app_meeting_status:
#    resource: "@AppBundle/Controller/MeetingStatusController.php"
#    type:     annotation
show_about:
  path: /about/
  defaults: {_controller: AppBundle:Main:about}
# Minute Action
edit_minute_action:
  path: /minuteaction/edit/{minuteItem}
  defaults: {_controller: AppBundle:MinuteAction:edit}
delete_minute_action:
  path: /minuteaction/delete/{minuteItem}/{minuteAction}
  defaults: {_controller: AppBundle:MinuteAction:delete}
new_minute_action:
  path: /minuteaction/new/{minuteItem}
  defaults: {_controller: AppBundle:MinuteAction:new}
# Conduct Meeting
finish_meeting:
  path: /conductmeeting/finish/{meeting}
  defaults: {_controller: AppBundle:ConductMeeting:finishMeeting}
presence_check:
  path: /conductmeeting/next/{meeting}/{agendaItem}/{meetingAttendance}
  defaults: {_controller: AppBundle:ConductMeeting:presenceCheck}
next_agenda_on_meeting:
#  path: /conductmeeting/next/{meeting}/{agendaItem}
  path: /conductmeeting/next/{meeting}/{agendaItemSequenceNo}
  defaults: {_controller: AppBundle:ConductMeeting:next}
start_meeting:
  path: /conductmeeting/start/{meeting}
  defaults: {_controller: AppBundle:ConductMeeting:start}
#Agenda item
make_current_agenda_item:
  path: /agendaitem/makeitcurrent/{agendaItem}
  defaults: {_controller: AppBundle:AgendaItem:makeCurrent}
show_agenda_item:
  path: /agendaitem/{agendaItem}
  defaults: {_controller: AppBundle:AgendaItem:show}
new_agenda_item:
  path: /agendaitem/new/{meeting}
  defaults: {_controller: AppBundle:AgendaItem:new}
# Meeting section
new_meeting:
  path: /meeting/new/{project}
  defaults: {_controller: AppBundle:Meeting:new}
show_meeting:
  path: /meeting/meeting/{meeting}
  defaults: {_controller: AppBundle:Meeting:show}
new_project:
  path: /project/newproject
  defaults: {_controller: AppBundle:Project:new}
remove_user_from_project:
  path: /project/removeuserfromproject/{project}/{user}
  defaults: {_controller: AppBundle:ProjectHasUser:remove}
# Project has user section

add_user_to_current_project:
  path: /project/addusertoproject/{project}
  defaults: {_controller: AppBundle:ProjectHasUser:addTo}
add_user_to_project:
  path: /project/addusertoproject
  defaults: {_controller: AppBundle:ProjectHasUser:add}
# Project section
show_project:
  path: /project/{project}
  defaults: {_controller: AppBundle:Project:show}
delete_project:
    path: /project/deleteproject/{project}
    defaults: {_controller: AppBundle:Project:delete}
turn_project_lock:
    path: /project/turnprojectlock/{project}
    defaults: {_controller: AppBundle:Project:turnLock}
# Project role section
new_project_role:
    path: /role/newrole
    defaults: {_controller: AppBundle:Role:new}
delete_role:
    path: /role/deleterole/{projectRole}
    defaults: {_controller: AppBundle:Role:delete}
# Admin section
new_user:
    path: /admin/newuser
    defaults: {_controller: AppBundle:Admin:new}
edit_user:
    path: /admin/edituser/{userID}
    defaults: {_controller: AppBundle:Admin:edit}
delete_user:
    path: /admin/deleteuser/{userID}
    defaults: {_controller: AppBundle:Admin:delete}
# MAIN CONTROLLER section
sup_panel:
    path: /sup/suppanel
    defaults: {_controller: AppBundle:Main:supPanel}
user_panel:
    path: /user/userpanel
    defaults: {_controller: AppBundle:Main:userPanel}
homepage:
    path: /
    defaults: {_controller: AppBundle:Main:homepage}
admin_panel:
    path: /admin/adminpanel
    defaults: {_controller: AppBundle:Main:adminPanel}
logout:
    path: /logout
    defaults: {_controller: AppBundle:Main:logout}

