homepage:
    path: /
    defaults: {_controller : AppBundle:Main:homepage}
logout:
    path: /logout
    defaults: {_controller : AppBundle:Main:logout}
new_user:
    path: /admin/newuser
    defaults: {_controller : AppBundle:User:new}
edit_user:
    path: /admin/edituser/{userId}
    defaults: {_controller : AppBundle:User:edit}
delete_user:
    path: /admin/deleteuser/{userId}
    defaults: {_controller : AppBundle:User:delete}