homepage:
    path: /
    defaults: {_controller : AppBundle:Main:homepage}
logout:
    path: /logout
    defaults: {
      _controller : AppBundle:Main:logout
      }

user_panel:
    path: /user/userpanel
    defaults: {_controller : AppBundle:Main:userPanel}
#Supervisor section
new_project:
    path: /project/newproject
sup_panel:
    path: /sup/suppanel
    defaults: {_controller : AppBundle:Main:supPanel}
#Admin section
admin_panel:
    path: /admin/adminpanel
    defaults: {_controller : AppBundle:Admin:adminPanel}
new_user:
    path: /admin/newuser
    defaults: {_controller : AppBundle:Admin:new}
edit_user:
    path: /admin/edituser/{userID}
    defaults: {_controller : AppBundle:Admin:edit}
delete_user:
    path: /admin/deleteuser/{userID}
    defaults: {_controller : AppBundle:Admin:delete}
