# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

#ROLE_NEW_PROJECT
#ROLE_LOCK_PROJECT
#ROLE_SHOW_PROJECT
#ROLE_DELETE_PROJECT
#ROLE_ADD_USER_TO_PROJECT
#ROLE_ADD_USER_TO_CURRENT_PROJECT
#ROLE_REMOVE_USER_FROM_PROJECT
#ROLE_SHOW_MEETING
#ROLE_NEW_MEETING
#ROLE_NEW_AGENDA_ITEM
#ROLE_MAKE_AGENDA_ITEM_CURRENT
#ROLE_SHOW_AGENDA_ITEM
#ROLE_START_MEETING
#ROLE_FINISH_MEETING

    role_hierarchy:
        ROLE_ADMIN: [ROLE_NEW_USER, ROLE_EDIT_USER, ROLE_DELETE_USER]
        ROLE_USER: [ROLE_FINISH_MEETING, ROLE_START_MEETING,ROLE_MAKE_AGENDA_ITEM_CURRENT, ROLE_REMOVE_USER_FROM_PROJECT, ROLE_ADD_USER_TO_CURRENT_PROJECT, ROLE_NEW_MEETING, ROLE_NEW_AGENDA_ITEM, ROLE_SHOW_AGENDA_ITEM, ROLE_SHOW_MEETING, ROLE_SHOW_PROJECT]
        ROLE_SUPERVISOR: [ROLE_FINISH_MEETING, ROLE_START_MEETING, ROLE_LOCK_PROJECT, ROLE_MAKE_AGENDA_ITEM_CURRENT, ROLE_SHOW_AGENDA_ITEM, ROLE_NEW_AGENDA_ITEM, ROLE_SHOW_MEETING, ROLE_NEW_MEETING, ROLE_REMOVE_USER_FROM_PROJECT, ROLE_ADD_USER_TO_CURRENT_PROJECT, ROLE_SHOW_PROJECT, ROLE_ADD_USER_TO_PROJECT, ROLE_NEW_PROJECT, ROLE_NEW_PROJECT_ROLE, ROLE_DELETE_PROJECT_ROLE, ROLE_REMOVE_USER_FROM_PROJECT]
    providers:
        in_memory:
            memory: ~
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
